[package]
name = "yahmc"
version = "0.1.0"
authors = ["Ranie Jade Ramiso <raniejaderamiso@gmail.com>"]

[dependencies]
engine = { path = "engine" }
simple_logger = "0.5.0"

[workspace]
members = [".", "engine", "ecs", "ecs_derive", "ecs2"]