[package]
name = "ecs"
version = "0.1.0"
authors = ["Ranie Jade Ramiso <raniejaderamiso@gmail.com>"]

[dependencies]
log = "0.4.0"
mopa = "0.2.2"
fxhash = "0.2.1"
bit-set = "0.4.0"
ecs_derive = { path = "../ecs_derive" }

[dev-dependencies]